### ISSUE TITLE
I put blocks ..

### ISSUE THREAD

**Issue by Tsyklop** [MattCzyr/RealisticTorches#1]
I take the lighter. I put in the first slot hotbar any block. RBC click on the torch and the block is placed.

**Comment by MattCzyr** [comment]
So far I have not been able to recreate this. Which version of the mod are you using, and do you have any other mods installed? Can you give specific steps to recreate the issue?

**Comment by Tsyklop** [comment]
RealisticTorches-1.7.10-1.2.0

I put Until Torch. I take the lighter and box it in hotbar. I take any block and a box to the right of lighters in hotbar. Next.I incinerate Until Torch while I put a block.

I noticed that when the unit is either right or left of the lighter it will be put

**Comment by MattCzyr** [comment]
Still unable to recreate, using v1.2.0, no other mods loaded. The steps I've used to try to create the issue:
1. Put flint and steel, a block, and an unlit torch in the hotbar (typically in that order, but I have tried others)
2. Place an unlit torch
3. Right click the unlit torch with the flint and steel

Seems to work as intended. Are these the correct steps?

**Comment by Tsyklop** [comment]
@ChaosTheDude https://youtu.be/Gy876UwpglY

**Comment by MattCzyr** [comment]
I see, thanks for showing me. Unfortunately I still haven't been able to recreate this, doing exactly as you showed in the video (and there's not much I can fix without being able to recreate the issue myself). This leads me to believe that it might be some kind of incompatibility with another of your mods. Could you  post a list of mods that you are using (or a link to the modpack if it is public) and/or try to recreate this yourself with no other mods loaded?

**Comment by Tsyklop** [comment]
OU. Launched without the other mods. Everything is fine.

The list of mods http://pastebin.com/16Pb3zp1 (The list of mods took a crash log))

Which events can influence it?

**Comment by MattCzyr** [comment]
Hard to say. I would try launching the game with half of the mods and see if the issue occurs - if it does, try with half of those mods, otherwise try the other half. Just keep halving the mods until you find the one that is causing the issue. Off the top of my head I can tell you that it is probably not any of the big, popular mods in your pack (Thermal Expansion, Mekanism, Buildcraft, etc) because I've tested the mod in packs containing those and did not come across this issue. In the mean time I'll test with some of the mods that I haven't tried with before.

**Comment by Tsyklop** [comment]
@ChaosTheDude Okay. I try

**Comment by MattCzyr** [comment]
Any luck narrowing it down?

**Comment by Tsyklop** [comment]
@ChaosTheDude I have not tried it yet. No time. I will try on the weekend. as the news will immediately let you know.

**Comment by MattCzyr** [comment]
Oh, alright. No rush.

**Comment by Tsyklop** [comment]
I found it. It can do two mods: ShadowTweaks and SurvivalTweaks Excuse for troubling.

**Comment by MattCzyr** [comment]
Noted, I will take a look and see if there's anything I can do on my end in terms of compatibility.
