### ISSUE TITLE
Torches Don't Respect Config for Burning Out Time

### ISSUE THREAD

**Issue by Amaxter** [MattCzyr/RealisticTorches#10]
Setting the config for torch burn out time to a negative value (-1) does not allow the torches to stay on indefinitely, they still burn out.

**Comment by MattCzyr** [comment]
Right now, if you place a torch and change the burnout config value to -1 afterwards, the torch will still burn out as it relies on the value at the time of placing. They will also still burn out in the rain. Could the torches you checked have either (A) been placed prior to changing the config value, or (B) been rained on? Either way, I'll sort both of those inconsistencies out.

In addition, what version of the mod are you using?
