### ISSUE TITLE
SpecialSource ASM5 breaks mod (NoClassDefFoundError: net/md_5/specialsource/transformer/MappingTransformer)

### ISSUE THREAD

**Issue by Smurfgar** [MattCzyr/RealisticTorches#14]
I actually messed up my testing. It actually works fine. :)

**Comment by MattCzyr** [comment]
The 1.7.10 version of this mod is no longer being maintained. However, it seems like it is an issue solely between Thermos/Spigot and SpecialSource that just happens to be triggered by a Realistic Torches during preinit. I'm not sure there's anything I could do about this anyway, except disable moving light sources completely (the error occurs when the tile entity is being registered).
