### ISSUE TITLE
[1.12.2] Matchbox durability ignores config

### ISSUE THREAD

**Issue by Ithronyar** [MattCzyr/RealisticTorches#18]
Changing the matchbox's durability in the config doesn't do anything. I tried setting it to 16, and it still had 64 uses. I tried 1000; still 64 uses. I tried -1; still 64.

**Comment by cameron-doyle** [comment]
I've had an issue where if you set it to a negative value the match box will disappear on use.

**Comment by MattCzyr** [comment]
Has been fixed as of version 2.1.2.
