### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by PalePyth** [MattCzyr/RealisticTorches#2]
The torches become unlit sometimes while holding.
https://media.giphy.com/media/3o85xz0wzHTBbtZXUY/giphy.gif

**Comment by MattCzyr** [comment]
To me, it looks like the chunks around you unloaded when the light was extinguished. Can you verify that the chunks (specifically the one you are in) are loaded when the issue occurs?

**Comment by PalePyth** [comment]
I think you are right.
24 нояб. 2015 г. 21:26 пользователь "ChaosTheDude" notifications@github.com
написал:

**Comment by MattCzyr** [comment]
If the chunk you are in is unloaded, there will be no light around you, as there will be nowhere for the light to exist and nothing for the light to illuminate.

If you can find the root of your chunk unloading (perhaps insufficient memory allocated) and fix it, handheld light sources should behave normally.
