### ISSUE TITLE
with noRelight on true, not all torches are destroyed by rain

### ISSUE THREAD

**Issue by Deliphin** [MattCzyr/RealisticTorches#27]
Before toggling rain:
![2020-02-24_21 42 18](https://user-images.githubusercontent.com/14265753/75207356-d02e9200-574e-11ea-8b9b-1c66235cfca5.png)

After toggling rain:
![2020-02-24_21 42 52](https://user-images.githubusercontent.com/14265753/75207358-d0c72880-574e-11ea-851f-51448f0f4f43.png)

My realistictorches.cfg: https://pastebin.com/HTGnznVL

I want them to all be destroyed, as I'm building an adventure server, and want to give players torches they can place anywhere, but don't last forever.

I do have other mods in this pack, but none of them are related to weather or should have any effect on this. If needed I can re-test with just realistic torches.

**Comment by MattCzyr** [comment]
Has been fixed as of version 2.1.2.
