### ISSUE TITLE
Lag when attempting to light Unlit torch under rain

### ISSUE THREAD

**Issue by Jomik** [MattCzyr/RealisticTorches#3]
I am getting a lag spike every time I attempt to light an Unlit torch under rain. Works just fine if the torch is covered. I am aware that the torch shouldn't be lit, but it's kinda annoying that the whole game throws a lag spike if I attempt to do it.

**Comment by MattCzyr** [comment]
Can you confirm that you are using the latest version (1.5.0)? Also, what MC version?

**Comment by Jomik** [comment]
Indeed;
RT: RealisticTorches-1.8.9-1.5.0
MC: 1.8.9-forge1.8.9-11.15.1.1761

**Comment by MattCzyr** [comment]
Fixed in version 1.5.1.
