### ISSUE TITLE
Moltiplication of matchboxes!

### ISSUE THREAD

**Issue by Azarilh** [MattCzyr/RealisticTorches#38]
When you merge two matchboxes, you can get the new merged one AND the two original ones.
![Screenshot_20210121_063531](https://user-images.githubusercontent.com/40278785/105284568-0967c000-5bb3-11eb-9b15-6216557b7bc4.png)
![Screenshot_20210121_063535](https://user-images.githubusercontent.com/40278785/105284583-11bffb00-5bb3-11eb-9a3a-5287d24bbd27.png)
![Screenshot_20210121_063538](https://user-images.githubusercontent.com/40278785/105284602-1a183600-5bb3-11eb-815e-a9881ca0b5ea.png)
![Screenshot_20210121_063541](https://user-images.githubusercontent.com/40278785/105284620-22707100-5bb3-11eb-9d74-3b8e5e5f7f4f.png)

**Comment by MattCzyr** [comment]
What version are you using?

**Comment by Azarilh** [comment]
The latest, 3.1.1 on Minecraft 1.16.4, forge 35.1.36.

**Comment by MattCzyr** [comment]
Fixed in version 3.1.2.
