### ISSUE TITLE
[1.9] java.lang.IllegalAccessError since Forge build 1805

### ISSUE THREAD

**Issue by Radiant-Xyz** [MattCzyr/RealisticTorches#4]
RealisticTorches is crashing since Forge build 1805 with "net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class com.chaosthedude.realistictorches.config.ConfigHandler".
The last working build is 1804. Crash log attached.

[crash-2016-03-26_23.00.32-client.txt](https://github.com/ChaosTheDude/RealisticTorches/files/190667/crash-2016-03-26_23.00.32-client.txt)

**Comment by MattCzyr** [comment]
Fixed in version 1.5.3.
