### ISSUE TITLE
[1.16.5] Realistic Torches Causing Missing/Null Blocks

### ISSUE THREAD

**Issue by XxInvictus** [MattCzyr/RealisticTorches#43]
MC Version: 1.16.5
Forge Version: forge-1.16.5-36.1.24
Mods Installed:
- Realistic Torches 1.16.5-3.1.2
- Citadel 1.16.5-1.6.3
- Ice and Fire 1.16.4-2.1.6

Description:
There are random blocks around the map that are missing/null, the block shadow is there but the block is transparent and you can click-through it.

This occurs seemingly randomly in mountainous areas. In some Biomes all trees are missing and only their shadows on the ground are present. The issue is EXTREMELY prevalent when combined with Ice and Fire as the whole dragon nests are made of these "ghost" blocks.

I have isolated this problem to only when Realistic Torches is installed on the server.

Screenshots and Logs included.
![2021-05-26_22 40 50](https://user-images.githubusercontent.com/3955293/119667746-b8741b00-be75-11eb-893f-9ff5e09c481f.png)
![2021-05-26_22 39 25](https://user-images.githubusercontent.com/3955293/119667759-bad67500-be75-11eb-9000-710b86a22f69.png)
![2021-05-26_22 40 13](https://user-images.githubusercontent.com/3955293/119667764-bc07a200-be75-11eb-9df0-7d26e145b517.png)
[realistic_torches_testing_logs.zip](https://github.com/MattCzyr/RealisticTorches/files/6547006/realistic_torches_testing_logs.zip)

**Comment by MattCzyr** [comment]
I'll take a look. In the meantime, I suggest setting the `generateLitTorches` config option to false to hopefully prevent this from happening in newly generated chunks.

**Comment by XxInvictus** [comment]
I think it is pretty safe to close this, it is very old and I am currently using these three mods with no issue in another pack and updated versions on 1.16.5
