### ISSUE TITLE
Realistic Torches erroring on Server for version 3.1.3 & 3.1.4

### ISSUE THREAD

**Issue by KaiLunis** [MattCzyr/RealisticTorches#47]
Idk they told me to contact you even though its a server issue and it is running perfectly fine on the client. Anyways.. Heres a pastebin of the error I guess?
I couldnt fit the whole error log in there so i just put this bit, i can post more if need be
https://pastebin.com/JdY3W9Vq

**Comment by MattCzyr** [comment]
Fixed in latest version, 3.1.5.
