### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Wolf68k** [MattCzyr/RealisticTorches#5]
This mod is a nice replacement for the Unlit Torches mod.
But it would nice if:
- You could hold a lit torch when a mod like Dynamic Lights is in the pack, more so with Hardcore Darkness as well. Holding the lit torch gives off light.
- Light torches by touching them to lava or other lit torches.

Sorry if this is the wrong way to make these suggestions. I have a few others about having lit torches in the player inventory if you're interested.

**Comment by MattCzyr** [comment]
Suggestions would fit better for either the MC Forum thread or the Curse/CurseForge project. Maybe even a pull request tagged as a suggestion, if that works better for you. But anyway:

I'm not completely sure what you mean by your first suggestion. If you mean torches emitting light when you hold them, that's already a feature -- all light-emitting blocks and a certain set of items will (by default) emit light when held. If that's not what you mean, please elaborate a bit.

I'm always interested in suggestions! Of course I cannot guarantee that I will add them, but I'm always looking for new ways to improve the mod, so feel free to let me know of any other suggestions you may have.
