### ISSUE TITLE
Breaking torch crashes game

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [MattCzyr/RealisticTorches#6]
So, one of our users broke an unlit torch while it was raining. The torch was hanging from a clay block if that helps.

[23:25:31] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[up, north, south, west, east]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
  at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137) ~[ama$a.class:?]
  at net.minecraft.block.BlockTorch.func_176201_c(BlockTorch.java:256) ~[akf.class:?]
  at com.chaosthedude.realistictorches.blocks.te.TETorch.func_73660_a(TETorch.java:22) ~[TETorch.class:?]
  at net.minecraft.world.World.func_72939_s(World.java:1716) ~[adm.class:?]
  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544) ~[le.class:?]
  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
  ... 4 more

**Comment by MattCzyr** [comment]
What Minecraft version was this, and what version of Realistic Torches?

If you have a full crash report from this, post that; it will have all the information I need.

**Comment by TheOnlySilverClaw** [comment]
As you wish:

<username>, [03.05.16 15:48]
A detailed walkthrough of the error, its code path and all known details is as follows:
—-------------------------------------------------------------------------------------

— Head —
Stacktrace:
  at net.minecraft.item.ItemStack.func_77980_a(ItemStack.java:415)
  at net.minecraft.inventory.SlotCrafting.func_75208_c(SlotCrafting.java:52)
  at net.minecraft.inventory.SlotCrafting.func_75210_a(SlotCrafting.java:45)
  at net.minecraft.inventory.Slot.func_75220_a(Slot.java:34)
  at net.minecraft.inventory.ContainerWorkbench.func_82846_b(SourceFile:96)
  at net.minecraft.inventory.Container.func_75144_a(Container.java:246)
  at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:488)
  at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:629)
  at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:388)
  at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:554)
  at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:523)

— Affected screen —
Details:
  Screen name: net.minecraft.client.gui.inventory.GuiCrafting

— Affected level —
Details:
  Level name: MpServer
  All players: 2 total; [EntityPlayerSP['Sirukal'/127125, l='MpServer', x=976,43, y=63,50, z=1115,00], EntityOtherPlayerMP['Anaeijon'/179043, l='MpServer', x=1056,09, y=64,00, z=1163,69]]
  Chunk stats: MultiplayerChunkCache: 441, 441
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: 439,00,66,00,302,00 - World: (439,66,302), Chunk: (at 7,4,14 in 27,18; contains blocks 432,0,288 to 447,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 3472219 game time, 3852138 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 31 total; [EntityPlayerSP['Sirukal'/127125, l='MpServer', x=976,43, y=63,50, z=1115,00], EntitySheep['Sheep'/126481, l='MpServer', x=960,38, y=63,00, z=1177,09], EntitySheep['Sheep'/126480, l='MpServer', x=966,75, y=63,00, z=1178,09], EntityBat['Bat'/181790, l='MpServer', x=1034,65, y=36,38, z=1175,46], EntityOtherPlayerMP['Anaeijon'/91239, l='MpServer', x=1049,84, y=63,00, z=1172,13], EntityBat['Bat'/175140, l='MpServer', x=950,56, y=49,10, z=1121,59], EntityBat['Bat'/182071, l='MpServer', x=1038,50, y=37,75, z=1175,53], EntitySquid['Squid'/181815, l='MpServer', x=940,28, y=62,13, z=1154,03], EntityBat['Bat'/181064, l='MpServer', x=1039,16, y=31,54, z=1168,17], EntitySquid['Squid'/178766, l='MpServer', x=936,50, y=62,19, z=1095,16], EntityOtherPlayerMP['Anaeijon'/179043, l='MpServer', x=1056,09, y=64,00, z=1163,69], EntityBat['Bat'/182134, l='MpServer', x=943,50, y=13,03, z=1087,13], EntitySquid['Squid'/182142, l='MpServer', x=987,59, y=62,10, z=1139,97], EntityBoat['Boat'/119678, l='MpServer', x=1033,91, y=62,90, z=1168,75], EntityOtherPlayerMP['Anaeijon'/179043, l='MpServer', x=1056,09, y=64,00, z=1163,69], EntityBat['Bat'/181903, l='MpServer', x=1035,45, y=20,18, z=1063,44], EntityBat['Bat'/182416, l='MpServer', x=949,23, y=11,11, z=1086,46], EntityCow['Cow'/127129, l='MpServer', x=899,91, y=63,00, z=1137,00], EntityCow['Cow'/127131, l='MpServer', x=901,44, y=65,00, z=1152,63], EntityMinecartChest['container.minecart'/127134, l='MpServer', x=911,50, y=16,06, z=1066,50], EntityBat['Bat'/182180, l='MpServer', x=944,75, y=14,10, z=1072,25], EntityBat['Bat'/182443, l='MpServer', x=911,13, y=17,10, z=1063,75], EntityBat['Bat'/182196, l='MpServer', x=970,69, y=11,00, z=1069,38], EntitySquid['Squid'/180678, l='MpServer', x=1012,53, y=61,97, z=1142,94], EntitySquid['Squid'/180676, l='MpServer', x=1015,50, y=59,00, z=1144,47], EntitySquid['Squid'/180683, l='MpServer', x=1019,53, y=60,72, z=1156,06], EntityCow['Cow'/126924, l='MpServer', x=917,06, y=63,00, z=1149,97], EntityBat['Bat'/181217, l='MpServer', x=1031,50, y=49,94,
<user name>, [03.05.16 15:48]
z=1195,84], EntityBat['Bat'/182762, l='MpServer', x=908,25, y=22,99, z=1191,89], EntitySheep['Sheep'/126457, l='MpServer', x=968,31, y=65,00, z=1192,44], EntitySheep['Sheep'/126456, l='MpServer', x=963,44, y=65,00, z=1190,63]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server
Stacktrace:
  at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
  at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
  at net.minecraft.client.main.Main.main(SourceFile:124)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:483)
  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

— System Details —
Details:
  Minecraft Version: 1.8.9
  Operating System: Windows 10 (amd64) version 10.0
  CPU: 4x AMD A10-6700 APU with Radeon(tm) HD Graphics 
  Java Version: 1.8.0_25, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 115512840 bytes (110 MB) / 784572416 bytes (748 MB) up to 1060372480 bytes (1011 MB)
  JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 97
  FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_H5 24 mods loaded, 24 mods active
  States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
  UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
  UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1722.jar) 
  UCHIJA  Forge{11.15.1.1722} [Minecraft Forge](forge-1.8.9-11.15.1.1722.jar) 
  UCHIJA  additionalbanners{1.1.1} [Additional Banners](AdditionalBanners-1.1.1-1.8.9.jar) 
  UCHIJA  AppleCore{1.3.0} [AppleCore](AppleCore-mc1.8.9-1.3.0.jar) 
  UCHIJA  AutoSapling{1.0} [Auto Sapling](AutoSapling 1.2 MC1.8.9.jar) 
  UCHIJA  BaMsGRAVE{2.0.1} [BaM's Grave](BaMsGRAVE-1.8.9-2.0.1.jar) 
  UCHIJA  BetterHorseHud{1.0} [Better Horse Hud](BetterHorseHud-1.8.9-1.0.jar) 
  UCHIJA  Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.8.8-1.4.jar) 
  UCHIJA  cfm{3.6.2} [MrCrayfish's Furniture Mod](cfm-3.6.2-mc1.8.9.jar) 
  UCHIJA  ModName{1.0.0} [ModName](CraftableGlowstone[1.8.9].jar) 
  UCHIJA  EnderZoo{1.8.9-1.1.3.35} [Ender Zoo](EnderZoo-1.8.9-1.1.3.35.jar) 
  UCHIJA  haggismod{1.4.2} [AWH Haggis Mod!](haggismod-1.4.2-mc1.8.jar) 
  UCHIJA  highlands{1.8.9} [Highlands](highlands-3.1.0.jar) 
  UCHIJA  hopperducts{1.4.6} [Hopper Ducts](hopperducts-mc1.8.8-1.4.6.jar) 
  UCHIJA  inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks](InventoryTweaks-1.60-40.jar) 
  UCHIJA  RealisticTorches{1.5.4} [Realistic Torches](RealisticTorches-1.8.9-1.5.4.jar) 
  UCHIJA  redstonepaste{1.7.2} [Redstone Paste](redstonepaste-mc1.8.8-1.7.2.jar) 
  UCHIJA  reforged_cag{1.0} [Reforged - Cross & Grave](reforged_cag-1.8.9-0.8.jar) 
  UCHIJA  SaltMod{1.8.b} [Salty Mod](SaltyMod-1.8.8-1.8.9-1.8.b.jar) 
  UCHIJA  SpiceOfLife{1.3.1} [The Spice of Life](SpiceOfLife-mc1.8.9-1.3.1.jar) 
  UCHIJA  VeinMiner{0.31.4_build.unknown} [Vein Miner](VeinMiner-1.8.9_31.4.jar) 
  UCHIJA  VeinMinerModSupport{0.31.4_build.unknown} [Mod Support](VeinMiner-1.8.9_31.4.jar) 
  UCHIJA  XaeroMinimap{1.8.7} [Xaero's Minimap](Xaeros_Minimap_1.8.7_Forge_1.8.9.jar) 
  Loaded coremods (and transformers): 
NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  lumien.bloodmoon.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.60-40.jar)

<user name>, [03.05.16 15:48]
invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.8.9-1.3.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 8670D'
  Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
  LWJGL: 2.9.4
  OpenGL: AMD Radeon HD 8670D GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

  Using VBOs: No
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (UK)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD A10-6700 APU with Radeon(tm) HD Graphics 
  OptiFine Version: OptiFine_1.8.9_HD_U_H5
  Render Distance Chunks: 16
  Mipmaps: 4
  Anisotropic Filtering: 1
  Antialiasing: 0
  Multitexture: false
  Shaders: null
  OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
  OpenGlRenderer: AMD Radeon HD 8670D
  OpenGlVendor: ATI Technologies Inc.
  CpuCount: 4

**Comment by MattCzyr** [comment]
Sorry about the delay. This should be fixed in version 1.5.6.
