### ISSUE TITLE
com.chaosthedude.realistictorches.blocks.te.TEMovingLightSource cannot be cast to com.mia.props.common.TileFake

### ISSUE THREAD

**Issue by lightning02** [MattCzyr/RealisticTorches#7]
The client crash when tryng to put down a Piano from decocraft "near" a torch (not lighted up)
http://pastebin.com/M0bdJKbP
I guess it crash with other various object from decocraft. Should I report the issue to decocraft dev too?

**Comment by MattCzyr** [comment]
Fixed in version 1.6.3.

**Comment by lightning02** [comment]
Really thanks a lot!!! Thanks for the fix but thanks even more for have done a fix for 1.7.10 version!!
